SOA-SVSB/config/routes.rb
SoaSvsb::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root :to => "product#index"
	resources :product

end

SOA-SVSB/app/models/product.rb
class Product < ActiveRecord::Base
	attr_accessible :productname, :description, :quantity, :maxprice, :location, :deadline, :user_id, :pic, :pic_file_name, :pic_content_type, :pic_file_size, :pic_updated_at, :category
has_attached_file :pic, :styles => 
        { :medium => "300x300>", :thumb => "100x100>" }
#has_attached_file :attach

	belongs_to :user
end

SOA-SVSB/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :gender, :image, :provider, :uid, :total_rank
  # attr_accessible :title, :body
  has_many :products

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
													 image:auth.info.image,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

SOA-SVSB/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

SOA-SVSB/app/controllers/product_controller.rb
class ProductController < ApplicationController

	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

	def index
  	@product = Product.all
	end

	def new
  	@product = Product.new
	end

	def create
		@product = Product.new(params[:product])
		@product.save

		redirect_to product_index_path
	end

	def edit
  	@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		@product.update_attributes(params[:product])

		redirect_to product_path(@product) # action=> :show
	end

	def show
  	@product = Product.includes(:user).find(params[:id])

  	@user = User.includes(:product).find(@product.id)

		respond_to do |format|
		  format.html # show.html.erb
		  format.xml  { render :xml => @product }
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to product_index_path
	end

	def search

	end

end

SOA-SVSB/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

SOA-SVSB/app/helpers/application_helper.rb
module ApplicationHelper
end

SOA-SVSB/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
        <title>GrouPurchase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
        <!-- Navigator section -->

        <div class="container my_container_header">
                <div class="navbar-header">
                   
                        <a>
<img class="logo_brand"  style="width:100px;" src=http://lipshipsandfashiontips.files.wordpress.com/2013/04/lovebulkbutton.png>
                        </a>
<!--Love Bulk Logo image-->
                                                 
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                        </button>
                </div>
                <!-- creates and places the three buttons to top right of the navigation bar (login, sign up and new product) -->


               
                <div class="collapse header_collapse navbar-collapse navbar-ex1-collapse">

                        <ul class="nav navbar-nav navbar-right ">
                               
                                <li class="navbar_list">

<% if current_user %>
        <%= link_to('logout', destroy_user_session_path, :method => :delete, :class=>"btn btn-danger header_btn", :id=>"add_dish") %>

<% else %>
        <%= link_to('sign up', new_registration_path(:user), :class=>"btn btn-danger header_btn", :id=>"add_dish") %>
<% end %>
                              
                                </li>
  <!-- Creates hyperlink for sign up button to open sign up page and will appear as log out when user is signed in-->
                               

        <li class="navbar_list">
                <div class="dropdown">

<% if current_user %>
        <%= link_to('modify password', edit_registration_path(:user), :class=>"btn btn-danger header_btn", :id=>"login") %>
<% else %>
        <%= link_to('login', new_session_path(:user), :class=>"btn btn-danger header_btn", :id=>"login") %>
<% end %>
                                              
                                                                               
                </div>
        </li>

<!-- Creates hyperlink for login button to open login page and will appear as modify password when user is loged in-->
        

        <li class="navbar_list">
        <div class="dropdown">
                               
 <%= link_to('New product', new_product_path, :class=>"btn btn-danger", :id=>"my-account") %>

        </div>
        </li> 
<!-- Creates hyperlink for new product button to open new product page-->  

        <!-- /.navbar-collapse -->                   
                        </ul>
                </div>
        </div>
        <!-- /.navbar-collapse -->
</nav>
 
  
<div id="carousel-example-generic" class="carousel slide carousel_home">


        <!-- Wrapper for slides -->
       
        <div class="carousel-inner">
                <div class="item active bg_image1">

<!-- You can change the background picture of every page by changing the url of the bg_image class name here and adding the url of that class on the app.css. I am currently using bg_image1 (homepage) and bg_image2. bg_image3-5 are free so you can change the urls for these classes -->

<p></p>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
                        <%= yield %>

<!-- Content from other pages will appear in this yield area infront of the background image-->

                                
               
                </div>
        </div>
</div>

</body>
</html>

SOA-SVSB/app/views/product/edit.html.erb
<%= form_for @product, :url => product_path(@product.id), :method => :put do |f| %>
    <%= f.label :productname, "Product Name" %>
    <%= f.text_field :productname %>
		</br>
   <%= f.label :category, "Category" %>
    <%= f.select :category, [['Food','1'],['Toiletries','2'],['Stationary','3']] %>
		</br>
    <%= f.label :pic_id, "Picture Upload" %>
   	<%= f.file_field :pic %>
		</br>
    <%= f.label :quantity, "Quantity" %>
    <%= f.select :quantity,[['1','1'],['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7'],['8','8'],['9','9'],['10','10']] %>
		</br>
    <%= f.label :maxprice, "Max Price" %>
    <%= f.text_field :maxprice %>
		</br>
    <%= f.label :location, "Location" %>
    <%= f.select :location, [['Taipei','1'],['HsinChu','2'],['Taichung','3'],['Tainan','4'],['Kaohsiung','5'],['Eastern Taiwan','6']] %>
		</br>
    <%= f.label :deadline, "Deadline" %>
    <%= f.text_field :deadline %>
		</br>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :size=>"15x5" %>
		</br>
    <%= f.submit "Update" %>
<% end %>

SOA-SVSB/app/views/product/index.html.erb
<div id="carousel-example-generic" class="carousel slide carousel_home">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
                <div class="item active bg_image1">


<!--creates space between Welcom message and search bar -->

                        <div class=" col-lg-8 center_overlay">
                                <div class="form-group">
                                        <p class="home_margin text-center home_font">See what you can buy in bulk today</p>
                                        <input type="text" class="form-control" id="search_speciality" placeholder="Search for products">



                                </div>
<%= button_to 'Search' %>
                        </div>

        <!-- creates search bar -->

                

<div class="inc_container">
        <div class="row">
        <div class="heading_padding ">
<center>
                <p class="section_heading">Categories</p>
</center>
        </div>
        </div>
<div class="row component_padding_left">

         <div class="col-md-3 component_front component_margin_right component_margin_bottom ">
    <img class="img-circle foodies" src="http://daxueconsulting.com/wp-content/uploads/2012/08/daxue-consulting-instant-noodles.jpg" />
    <p class="foodie_name text-center">Food</p>
        </div>

    <div class="col-md-3 component_front component_margin_right component_margin_bottom ">
    <img class="img-circle foodies" src="http://static2.stuff.co.nz/1363555512/214/8439214.jpg" />
    <p class="foodie_name text-center">Toiletries</p>
    </div>

        <div class="col-md-3 component_front component_margin_right component_margin_bottom ">
    <img class="img-circle foodies" src="http://www.rajahmundry.me/Rajamahendravaram/uploads/20120430103100-1160079293-Stationaries2.jpg" />
    <p class="foodie_name text-center">Stationary</p>
    
        </div>

</div>
</div>

<div>
<% @product.each do |product| %>
  <li>
  <%= product.productname %>
        <%= image_tag "http://graph.facebook.com/#{current_user.uid}/picture?type=large" %>
  <%= link_to 'Show', product_path(product.id) %>
  <%= link_to 'Edit', edit_product_path(product.id) %>
  <%= link_to 'Delete', product_path(product.id), :method => :delete %>
  </li>
<% end %>
</div>
</div>
</div>

SOA-SVSB/app/views/product/new.html.erb
<%= form_for @product, :url => product_index_path(@product.id), :method => :post do |f| %>
    <%= f.label :productname, "Product Name" %>
    <%= f.text_field :productname %>
		</br>
    <%= f.label :category, "Category" %>
    <%= f.select :category, [['Food','1'],['Toiletries','2'],['Stationary','3']] %>
		</br>
    <%= f.label :pic_id, "Picture Upload" %>
   	<%= f.file_field :pic %>
		</br>
    <%= f.label :quantity, "Quantity" %>
    <%= f.select :quantity,[['1','1'],['2','2'],['3','3'],['4','4'],['5','5'],['6','6'],['7','7'],['8','8'],['9','9'],['10','10']] %>
		</br>
    <%= f.label :maxprice, "Max Price" %>
    <%= f.text_field :maxprice %>
		</br>
    <%= f.label :location, "Location" %>
    <%= f.select :location, [['Taipei','1'],['HsinChu','2'],['Taichung','3'],['Tainan','4'],['Kaohsiung','5'],['Eastern Taiwan','6']] %>
		</br>
    <%= f.label :deadline, "Deadline" %>
    <%= f.text_field :deadline %>
		</br>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :size=>"15x5" %>
		</br>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.submit "Create" %>
<% end %>

SOA-SVSB/app/views/product/show.html.erb
<div class=" col-lg-8 center_overlay">
	<div class="form-group">
		<div style="color:white; font:14px;">

		Requester: <%= @product.user.name %>
		</br>

		Product Name: <%= @product.productname %>
		</br>
 
		Category:
		<% case @product.category %>
			<% when '1' %>
			<%= "Food" %>
			<% when '2' %>
			<%= "Toiletries" %>
			<% when '3' %>
			<%= "Stationary" %>
			
		<% end %>
		</br>
		Product Photo: <%= image_tag @product.pic.url(:medium) %>
		</br>

		Quantity: <%= @product.quantity %>
		</br>

		Max. Acceptable Price: <%= @product.maxprice %>
		</br>

		Location / District: 
		<% case @product.location %>
			<% when '1' %>
			<%= "Taipei" %>
			<% when '2' %>
			<%= "HsinChu" %>
			<% when '3' %>
			<%= "Taichung" %>
			<% when '4' %>
			<%= "Tainan" %>
			<% when '5' %>
			<%= "Kaohsiung" %>
			<% when '6' %>
			<%= "Eastern Taiwan" %>
		<% end %>
		</br>

		Request Dealine: <%= @product.deadline %>
		</br>

		Discriptions: <%= simple_format(@product.description) %>

		<div id="fb-root"></div>
		<script>
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=189142694620805";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		</script>

		<div class="fb-like" data-href=<%= "http://soa-svsb.herokuapp.com/product/#{@product.id}"%> data-width="100" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>

		<div class="fb-comments" data-href=<%= "http://soa-svsb.herokuapp.com/product/#{@product.id}"%> data-width="600" data-numposts="5" data-colorscheme="light"></div>

		<p><%= link_to 'Back to homepage', product_index_path %></p>

</div>
</div>
</div>

SOA-SVSB/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>