config/routes.rb
SoaSvsb::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

	root :to => "request#index"
	resources :request

end

app/models/request.rb
class Request < ActiveRecord::Base
	attr_accessible :productname, :description, :quantity, :maxprice, :location, :deadline, :pic_id, :user_id
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :gender, :pic_id, :provider, :uid, :total_rank
  # attr_accessible :title, :body
  has_many :requests

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           email:auth.info.email,
                           password:Devise.friendly_token[0,20]
                           )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/request_controller.rb
class RequestController < ApplicationController

	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

	def index
  	@request = Request.all
	end

	def new
  	@request = Request.new
	end

	def create
		@request = Request.new(params[:request])
		@request.save

		redirect_to request_index_path
	end

	def edit
  	@request = Request.find(params[:id])
	end

	def update
		@request = Request.find(params[:id])
		@request.update_attributes(params[:request])

		redirect_to request_path(@request) # action=> :show
	end

	def show
  	@request = Request.includes(:user).find(params[:id])
	end

	def destroy
		@request = Request.find(params[:id])
		@request.destroy

		redirect_to request_index_path
	end

	def search
	end

end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GrouPurchase</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" role="navigation">
        <!-- Navigator section -->
        <div class="container my_container_header">
                <div class="navbar-header">
                        <a>
                        <p></p>
                        <p></p>
                        <p> <span style="font-size: 20px">WELCOME TO GROUP PURCHASE </span> </p>
                        </a>
                         
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                        </button>
                </div>
                <!-- moves the three buttons to top right -->
               
                <div class="collapse header_collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav navbar-right ">
                       
                                <li class="navbar_list">

<% if current_user %>
	<%= link_to('logout', destroy_user_session_path, :method => :delete, :class=>"btn btn-danger header_btn", :id=>"add_dish") %>
<% else %>
	<%= link_to('sign up', new_registration_path(:user), :class=>"btn btn-danger header_btn", :id=>"add_dish") %>
<% end %>

                               
                                        <!-- <a href="/dishes/new" class="btn btn-danger header_btn" id="add_dish">Sign Up</a> -->
                                </li>
                               
                                        <li class="navbar_list">
                                        <div class="dropdown">


<% if current_user %>
	<%= link_to('modify password', edit_registration_path(:user), :class=>"btn btn-danger header_btn", :id=>"login") %>
<% else %>
	<%= link_to('login', new_session_path(:user), :class=>"btn btn-danger header_btn", :id=>"login") %>
<% end %>

                                                        <!-- <a href="#" class="btn btn-danger" data-toggle="dropdown" id="login">Login</a> -->
                                               
                                                                               
                                        </div>
                                        </li>
                               
                               
                        </ul>
                </div>
        </div>
        <!-- /.navbar-collapse -->
</nav>
 
  <div >
  </div>
 
<div id="carousel-example-generic" class="carousel slide carousel_home">
<div class="carousel_overlay_div">
                <div class="container container_home">
                        <div class=" col-lg-8 center_overlay">
                                <div class="form-group">
                                        <p class="home_margin text-center home_font">See what people want to buy today</p>
                                        <input type="text" class="form-control" id="search_speciality" placeholder="Search for products">
                                </div>
                        </div>
                </div>
        </div>
        <!-- Wrapper for slides -->
       
        <div class="carousel-inner">
                <div class="item active bg_image2">
                        <div class="carousel-caption">
 
                                <p class=" text-center caption_font">"I'm going to buy Shampoo on Friday. Anyone want to buy in bulk a share?</p>
                                <b>
                                        <p class="carousel-dish-name">Busi</p>
                                </b>
                       
                        </div>
               
               
                </div>
        </div>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/request/edit.html.erb
<%= form_for @request, :url => request_path(@request.id), :method => :put do |f| %>
    <%= f.label :productname, "Product Name" %>
    <%= f.text_field :productname %>
		</br>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
		</br>
    <%= f.label :quantity, "Quantity" %>
    <%= f.text_field :quantity %>
		</br>
    <%= f.label :maxprice, "Max Price" %>
    <%= f.text_field :maxprice %>
		</br>
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %>
		</br>
    <%= f.label :deadline, "Deadline" %>
    <%= f.text_field :deadline %>
		</br>
    <%= f.label :pic_id, "Picture Upload" %>
    <%= f.text_field :pic_id %>
		</br>
    <%= f.submit "Update" %>
<% end %>

app/views/request/index.html.erb
<ul>
<% @request.each do |request| %>
  <li>
  <%= request.productname %>
  <%= link_to 'Show', request_path(request.id) %>
  <%= link_to 'Edit', edit_request_path(request.id) %>
  <%= link_to 'Delete', request_path(request.id), :method => :delete %>
  </li>
<% end %>
</ul>
<%= link_to 'New Request', new_request_path %>

app/views/request/new.html.erb
<%= form_for @request, :url => request_index_path(@request.id), :method => :post do |f| %>
    <%= f.label :productname, "Product Name" %>
    <%= f.text_field :productname %>
		</br>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
		</br>
    <%= f.label :quantity, "Quantity" %>
    <%= f.text_field :quantity %>
		</br>
    <%= f.label :maxprice, "Max Price" %>
    <%= f.text_field :maxprice %>
		</br>
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %>
		</br>
    <%= f.label :deadline, "Deadline" %>
    <%= f.text_field :deadline %>
		</br>
    <%= f.label :pic_id, "Picture Upload" %>
    <%= f.text_field :pic_id %>
		</br>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.submit "Create" %>
<% end %>

app/views/request/show.html.erb
<%= @request.user.name %>
</br>

<%= simple_format(@request.productname) %>
</br>

<%= simple_format(@request.description) %>
</br>

<%= @request.quantity %>
</br>

<%= @request.maxprice %>
</br>

<%= simple_format(@request.location) %>
</br>

<%= simple_format(@request.deadline) %>
</br>

<p><%= link_to 'Back to index', request_index_path %></p>